version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/Lolo-Botsado
permissions:
  - object: /home/ec2-user/Lolo-Botsado/BotScripts/install_dependencies.sh
    owner: root
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: BotScripts/stop_bot.sh
      timeout: 300
      runas: ec2-user
  Install:
    - location: BotScripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: BotScripts/start_bot.sh
      timeout: 300
      runas: ec2-user
