version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/Lolo-Botsado
permissions:
  - object: /home/ec2-user/Lolo-Botsado/Scripts/install_dependencies.sh
    owner: root
    mode: 755
    type:
      - file
# hooks:
#   AfterInstall:
#     - location: scripts/install_dependencies.sh
#       runas: root
#     - location: scripts/restart_services.sh
#       timeout: 60
#       runas: root