version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/Lolo-Botsado
permissions:
  - object: /home/ec2-user/Lolo-Botsado/BotScripts/install_dependencies.sh
    owner: root
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: /home/ec2-user/Lolo-Botsado/BotScripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user